name: Terraform Apply

on:
  workflow_dispatch:

jobs:
  apply:
    name: Apply Terraform Plan
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.0

      # Step 3: Download Plan Artifact
      - name: Download Terraform Plan
        uses: actions/download-artifact@v3
        with:
          name: terraform-plan
          path: .

      # Step 4: Terraform Apply
      - name: Terraform Apply
        run: terraform apply tfplan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_vpc_cidr_block: ${{ vars.vpc_cidr_block }}
          TF_VAR_public_subnet_cidr_block: ${{ vars.public_subnet_cidr_block }}
          TF_VAR_my_ip: ${{ vars.my_ip }}
