name: Terraform Destroy

on:
  workflow_dispatch:

jobs:
  destroy:
    name: Destroy Terraform Resources
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.0

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_public_key: ${{ secrets.AWS_PUBLIC_KEY }}
          TF_VAR_vpc_cidr_block: ${{ vars.vpc_cidr_block }}
          TF_VAR_public_subnet_cidr_block: ${{ vars.public_subnet_cidr_block }}
          TF_VAR_my_ip: ${{ vars.my_ip }}
